#lang scheme
(define (make-account balance password)
  (define incorrect-attempts 0)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (call-the-cops)
     (lambda (x)
       (display "too many incorrect attempts. Cops will be called!")
       (newline)))
  (define (dispatch m user-password)
    (if (eq? password user-password)
        (begin
          (set! incorrect-attempts 0)
          (cond ((eq? m 'withdraw) withdraw)
                ((eq? m 'deposit) deposit)
                (else (error "Unknown request -- MAKE-ACCOUNT"
                             m))))
        (begin
          (set! incorrect-attempts (+ incorrect-attempts 1))
          (if (= incorrect-attempts 7)
              (begin
                (set! incorrect-attempts 0)
                (call-the-cops))
              (lambda (x)
                (display "Incorrect Password")
                (newline))))))
  dispatch)

(define acc (make-account 1000 'pwd123))
((acc 'withdraw 'pw123) 100)
((acc 'withdraw 'p123) 100)
((acc 'deposit 'p123) 200)
((acc 'withdraw 'p123) 100)
((acc 'withdraw 'p123) 100)
((acc 'withdraw 'p123) 100)
((acc 'withdraw 'p123) 100)