#lang sicp
(define (square x) (* x x))
(define (get_larger x y) 
(if (> x y) x y)
)
(define (get_smaller x y)
	(if (< x y) x y)
)
(define (sum_of_larger_squares x y z)
	(+ (square (get_larger x y)) (square (get_larger (get_smaller x y) z))) 
)
