#lang sicp
(define (sqrt n)
  (define (average x y)
    (/ (+ x y) 2)
  )
  (define (improve guess)
    (average  guess (/ n guess))
  )
  (define (good_enough? guess new_guess)
    (< (/ (abs (- new_guess guess)) guess) 0.0001)
  )
  (define (sqrt-iter guess)
    (define new_guess (improve guess))
    (if (good_enough? guess new_guess)
        guess
        (sqrt-iter new_guess)
    )
  )
  (sqrt-iter 1.0)
)
(sqrt 1000000)
(sqrt 2)
