(define (let? exp) (tagged-list exp 'let))
(define (let-body exp) (caddr exp))
(define (let-variable-names exp) (map analyze (map car (cadr exp))))
(define (let-variable-values exp) (map analyze (map cadr (cadr exp))))
(define (let->combination exp)
  '((make-lambda (let-variable-names exp) (let-body exp))
    (let-variable-values exp))
(define (analyze-let exp)
  (analyze-lambda (let->combination exp)))
